[package]
name = "motion_extension"
version = "1.0.0"
title = "Motion Extension"
description = "An Isaac Sim extension for motion control."

[dependencies]
"omni.kit.app" = {}  # Required for event subscriptions

[python]
module = "motion_extension"
