[package]
name = "motion_extension"
version = "1.0.0"
title = "Motion Extension"
description = "An Isaac Sim extension for motion control."

[[python.module]]
module = "motion_extension.motion_extension"
